del amethyst_block.png
del bamboo_block.png
del bamboo_block_top.png
del bone_block_side.png
del bone_block_top.png
del brain_coral_block.png
del brown_mushroom_block.png
del bubble_coral_block.png
del chain_command_block_back.png
del chain_command_block_back.png.mcmeta
del chain_command_block_conditional.png
del chain_command_block_conditional.png.mcmeta
del chain_command_block_front.png
del chain_command_block_front.png.mcmeta
del chain_command_block_side.png
del chain_command_block_side.png.mcmeta
del chiseled_quartz_block.png
del chiseled_quartz_block_top.png
del coal_block.png
del 
del command_block_back.png
del command_block_back.png.mcmeta
del command_block_conditional.png
del command_block_conditional.png.mcmeta
del command_block_front.png
del command_block_front.png.mcmeta
del command_block_side.png
del command_block_side.png.mcmeta
del copper_block.png
del dead_brain_coral_block.png
del dead_bubble_coral_block.png
del dead_fire_coral_block.png
del dead_horn_coral_block.png
del dead_tube_coral_block.png
del diamond_block.png
del dripstone_block.png
del emerald_block.png
del fire_coral_block.png
del grass_block_side.png
del grass_block_side_overlay.png
del grass_block_snow.png
del grass_block_top.png
del hay_block_side.png
del hay_block_top.png
del honeycomb_block.png
del honey_block_bottom.png
del honey_block_side.png
del honey_block_top.png
del horn_coral_block.png
del iron_block.png
del moss_block.png
del mushroom_block_inside.png
del netherite_block.png
del nether_wart_block.png
del note_block.png
del purpur_block.png
del quartz_block_bottom.png
del quartz_block_side.png
del quartz_block_top.png
del raw_copper_block.png
del raw_gold_block.png
del raw_iron_block.png
del red_mushroom_block.png
del repeating_command_block_back.png
del repeating_command_block_back.png.mcmeta
del repeating_command_block_conditional.png
del repeating_command_block_conditional.png.mcmeta
del repeating_command_block_front.png
del repeating_command_block_front.png.mcmeta
del repeating_command_block_side.png
del repeating_command_block_side.png.mcmeta
del slime_block.png
del stripped_bamboo_block.png
del stripped_bamboo_block_top.png
del structure_block.png
del structure_block_corner.png
del structure_block_data.png
del structure_block_load.png
del structure_block_save.png
del tube_coral_block.png
del warped_wart_block.png