ren coal_ore.png coal_ore.煤矿石.png
ren deepslate_coal_ore.png deepslate_coal_ore.深板岩煤矿石.png
ren iron_ore.png iron_ore.铁矿石.png
ren deepslate_iron_ore.png deepslate_iron_ore.深板岩铁矿石.png
ren gold_ore.png gold_ore.金矿石.png
ren deepslate_gold_ore.png deepslate_gold_ore.深板岩金矿石.png
ren diamond_ore.png diamond_ore.钻石矿石.png
ren deepslate_diamond_ore.png deepslate_diamond_ore.深板岩钻石矿石.png
ren emerald_ore.png emerald_ore.绿宝石矿石.png
ren deepslate_emerald_ore.png deepslate_emerald_ore.深板岩绿宝石矿石.png
ren redstone_ore.png redstone_ore.红石矿石.png
ren deepslate_redstone_ore.png deepslate_redstone_ore.深板岩红石矿石.png
ren lapis_ore.png lapis_ore.青金石矿石.png
ren deepslate_lapis_ore.png deepslate_lapis_ore.深板岩青金石矿石.png
ren copper_ore.png copper_ore.铜矿石.png
ren deepslate_copper_ore.png deepslate_copper_ore.深板岩铜矿石.png
ren nether_gold_ore.png nether_gold_ore.下界金矿石.png
ren nether_quartz_ore.png nether_quartz_ore.下界石英矿石.png